//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pelatihan_Mart.Util
{
    using System;
    using System.Collections.Generic;
    
    public partial class Barang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Barang()
        {
            this.Transaksis = new HashSet<Transaksi>();
        }
    
        public int id { get; set; }
        public string kode { get; set; }
        public string nama { get; set; }
        public System.DateTime expired_date { get; set; }
        public int jumlah { get; set; }
        public string satuan { get; set; }
        public int harga_satuan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaksi> Transaksis { get; set; }
    }
}
