//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pelatihan_Mart.Util
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaksi
    {
        public int id { get; set; }
        public string no_transaksi { get; set; }
        public System.DateTime tgl_transaksi { get; set; }
        public string nama_kasir { get; set; }
        public int total_bayar { get; set; }
        public int user_id { get; set; }
        public int pelanggan_id { get; set; }
        public int barang_id { get; set; }
    
        public virtual Barang Barang { get; set; }
        public virtual Pelanggan Pelanggan { get; set; }
        public virtual User User { get; set; }
    }
}
